name: Bug Report
description: Report a bug or issue with the autobiography template
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! This helps make the template better for everyone.
        
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: setup-method
    attributes:
      label: Setup Method
      description: How did you set up the template?
      options:
        - Automated setup script
        - Manual setup
        - Other
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered
      placeholder: Tell us what went wrong...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What should have happened instead?
      placeholder: Describe the expected behavior...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Error Messages or Logs
      description: Copy any error messages or relevant log output
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation and FAQ
          required: true
        - label: I have searched for similar issues
          required: true
